# tools/golden_gen/extract.ps1
# Mechanically extracts VERBATIM functions/tables/macros from the vendored
# SVT-AV1 tree (third_party/SVT-AV1) into svt_gen.c. Never edits extracted
# text except the ONE documented substitution noted below. Fails loudly if
# any required symbol cannot be located.
#
# Usage:  pwsh ./extract.ps1   (from this directory)
# Output: svt_gen.c  (gitignored? NO - committed output is regenerated by
#         running this script; see README.md)

$ErrorActionPreference = "Stop"

$repo = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$src  = Join-Path $repo "third_party\SVT-AV1\Source\Lib"

$files = @{
    "transforms.c"       = (Get-Content (Join-Path $src "Codec\transforms.c") -Raw)
    "inv_transforms.c"   = (Get-Content (Join-Path $src "Codec\inv_transforms.c") -Raw)
    "inv_transforms.h"   = (Get-Content (Join-Path $src "Codec\inv_transforms.h") -Raw)
    "intra_prediction.c" = (Get-Content (Join-Path $src "Codec\intra_prediction.c") -Raw)
    "intra_prediction.h" = (Get-Content (Join-Path $src "Codec\intra_prediction.h") -Raw)
    "enc_intra_prediction.c" = (Get-Content (Join-Path $src "Codec\enc_intra_prediction.c") -Raw)
    "filterintra_c.c"    = (Get-Content (Join-Path $src "C_DEFAULT\filterintra_c.c") -Raw)
    "intra_prediction_c.c" = (Get-Content (Join-Path $src "C_DEFAULT\intra_prediction_c.c") -Raw)
    "compute_sad_c.c"    = (Get-Content (Join-Path $src "C_DEFAULT\compute_sad_c.c") -Raw)
    "full_loop.c"        = (Get-Content (Join-Path $src "Codec\full_loop.c") -Raw)
    "definitions.h"      = (Get-Content (Join-Path $src "Codec\definitions.h") -Raw)
}
# normalize line endings to LF so multi-line patterns match regardless of
# how this script was saved
foreach ($k in @($files.Keys)) { $files[$k] = $files[$k].Replace("`r`n", "`n") }

function Find-Line([string]$text, [string]$pattern) {
    $pattern = $pattern.Replace("`r`n", "`n")
    $idx = $text.IndexOf($pattern, [System.StringComparison]::Ordinal)
    if ($idx -lt 0) { throw "symbol not found: $pattern" }
    $line = ($text.Substring(0, $idx) -split "`n").Count
    return @{ idx = $idx; line = $line }
}

# Extract a brace-balanced block starting at the line containing $pattern.
function Extract-Block([string]$text, [string]$pattern, [string]$label) {
    $loc = Find-Line $text $pattern
    $i = $text.IndexOf("{", $loc.idx)
    if ($i -lt 0) { throw "no opening brace for $label" }
    $depth = 0; $j = $i
    while ($j -lt $text.Length) {
        $c = $text[$j]
        if ($c -eq '{') { $depth++ }
        elseif ($c -eq '}') { $depth--; if ($depth -eq 0) { break } }
        $j++
    }
    if ($depth -ne 0) { throw "unbalanced braces for $label" }
    # include the remainder of the closing line (e.g. "} PredictionMode;")
    $lineEnd = $text.IndexOf("`n", $j)
    if ($lineEnd -lt 0) { $lineEnd = $text.Length }
    $end = $lineEnd
    $body = $text.Substring($loc.idx, $end - $loc.idx).TrimEnd()
    return @{ body = $body; line = $loc.line }
}

# Extract a preprocessor macro / scalar definition: from the pattern through
# its logical end (backslash continuations included), never crossing into
# unrelated constructs.
function Extract-Macro([string]$text, [string]$pattern, [string]$label) {
    $loc = Find-Line $text $pattern
    $lineStart = $text.LastIndexOf("`n", $loc.idx) + 1
    $pos = $lineStart
    while ($true) {
        $lineEnd = $text.IndexOf("`n", $pos)
        if ($lineEnd -lt 0) { $pos = $text.Length; break }
        $line = $text.Substring($pos, $lineEnd - $pos).TrimEnd("`r")
        $pos = $lineEnd + 1
        if (-not $line.TrimEnd().EndsWith('\')) { break }
    }
    $body = $text.Substring($lineStart, $pos - $lineStart).TrimEnd()
    return @{ body = $body; line = $loc.line }
}

function Emit-Macro([string]$file, [string]$pattern, [string]$label) {
    $r = Extract-Macro $files[$file] $pattern $label
    Emit ""
    Emit "// ==== SVT-AV1 $file :$($r.line) - $label (verbatim extract; do not edit) ===="
    Emit $r.body
}

$out = New-Object System.Text.StringBuilder
function Emit([string]$s) { [void]$out.AppendLine($s) }

function Emit-Verbatim([string]$file, [string]$pattern, [string]$label) {
    $r = Extract-Block $files[$file] $pattern $label
    Emit ""
    Emit "// ==== SVT-AV1 $file :$($r.line) - $label (verbatim extract; do not edit) ===="
    Emit $r.body
}

Emit "// ============================================================================"
Emit "// svt_gen.c - GENERATED by tools/golden_gen/extract.ps1 from the vendored"
Emit "// SVT-AV1 tree. Every marked block is a verbatim extract (provenance comment"
Emit "// above each). The only textual substitution in extracted code is the"
Emit "// get_filt_type shim inside build_intra_predictors, flagged inline below."
Emit "// Regenerate:  pwsh tools/golden_gen/extract.ps1"
Emit "// See tools/golden_gen/README.md for the provenance table."
Emit "// ============================================================================"
Emit "#include `"shims.h`""
Emit "#include <string.h>"
Emit "#include <stdio.h>"
Emit "#include <assert.h>"

# ---- definitions.h: enums / macros ----
Emit-Verbatim "definitions.h" "typedef enum ATTRIBUTE_PACKED {
    DC_PRED," "PredictionMode"

Emit-Verbatim "definitions.h" "typedef enum ATTRIBUTE_PACKED {
    FILTER_DC_PRED," "FilterIntraMode"

foreach ($d in @(
    @("definitions.h", "#define ROUND_POWER_OF_TWO(value, n)", "ROUND_POWER_OF_TWO"),
    @("definitions.h", "#define ROUND_POWER_OF_TWO_SIGNED(value, n)", "ROUND_POWER_OF_TWO_SIGNED"),
    @("definitions.h", "#define ANGLE_STEP", "ANGLE_STEP"))) {
    Emit-Macro $d[0] $d[1] $d[2]
}

# ---- inv_transforms.h: helpers ----
Emit-Macro "inv_transforms.h" "#define INV_COS_BIT" "INV_COS_BIT"
Emit-Macro "inv_transforms.h" "#define MAX_TXWH_IDX" "MAX_TXWH_IDX"
Emit-Verbatim "inv_transforms.h" "static const int8_t inv_cos_bit_col" "inv_cos_bit_col"
Emit-Verbatim "inv_transforms.h" "static const int8_t inv_cos_bit_row" "inv_cos_bit_row"
Emit-Macro "inv_transforms.h" "static const int32_t cos_bit_min" "cos_bit_min"
Emit-Verbatim "inv_transforms.c" "const int32_t svt_aom_eb_av1_cospi_arr_data" "svt_aom_eb_av1_cospi_arr_data"
Emit-Verbatim "inv_transforms.c" "const int32_t svt_aom_eb_av1_sinpi_arr_data" "svt_aom_eb_av1_sinpi_arr_data"
Emit-Verbatim "inv_transforms.h" "static INLINE const int32_t* cospi_arr" "cospi_arr"
Emit-Verbatim "inv_transforms.h" "static INLINE const int32_t* sinpi_arr" "sinpi_arr"
Emit-Verbatim "inv_transforms.h" "static INLINE int32_t round_shift" "round_shift"
Emit-Verbatim "inv_transforms.h" "static INLINE int32_t half_btf" "half_btf"

# ---- transforms.c: forward kernels + config rows ----
Emit-Verbatim "transforms.c" "static const int8_t fwd_shift_4x4" "fwd_shift_4x4"
Emit-Verbatim "transforms.c" "const int8_t fwd_cos_bit_col" "fwd_cos_bit_col"
Emit-Verbatim "transforms.c" "const int8_t fwd_cos_bit_row" "fwd_cos_bit_row"
Emit-Verbatim "transforms.c" "void svt_av1_fdct4_new" "svt_av1_fdct4_new"
Emit-Verbatim "transforms.c" "void svt_av1_fadst4_new" "svt_av1_fadst4_new"
Emit-Verbatim "transforms.c" "static const int8_t fwd_shift_8x8" "fwd_shift_8x8"
Emit-Verbatim "transforms.c" "void svt_av1_fdct8_new" "svt_av1_fdct8_new"
Emit-Verbatim "transforms.c" "void svt_av1_fadst8_new" "svt_av1_fadst8_new"

# ---- inv_transforms.c: clamp / inverse kernels ----
Emit-Verbatim "definitions.h" "static INLINE int64_t clamp64" "clamp64"
Emit-Verbatim "inv_transforms.c" "static const int8_t inv_shift_4x4" "inv_shift_4x4"
Emit-Verbatim "inv_transforms.c" "static const int8_t inv_shift_8x8" "inv_shift_8x8"
Emit-Verbatim "inv_transforms.c" "static INLINE int32_t clamp_value" "clamp_value"
Emit-Verbatim "inv_transforms.c" "static INLINE void clamp_buf" "clamp_buf"
Emit-Verbatim "inv_transforms.c" "void svt_av1_idct4_new" "svt_av1_idct4_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_iadst4_new" "svt_av1_iadst4_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_idct8_new" "svt_av1_idct8_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_iadst8_new" "svt_av1_iadst8_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_round_shift_array_c" "svt_av1_round_shift_array_c"

# ---- intra_prediction.c: intra machinery ----
Emit-Macro "intra_prediction.c" "const int32_t sm_weight_log2_scale" "sm_weight_log2_scale"
Emit-Verbatim "intra_prediction.c" "const uint8_t sm_weight_arrays" "sm_weight_arrays"
Emit-Macro "intra_prediction.c" "#define sm_weights_sanity_checks" "sm_weights_sanity_checks"
Emit-Verbatim "intra_prediction.c" "static const uint16_t eb_dr_intra_derivative" "eb_dr_intra_derivative"
Emit-Macro "intra_prediction.c" "#define divide_round" "divide_round"
Emit-Verbatim "intra_prediction.c" "static INLINE uint16_t get_dy" "get_dy"
Emit-Verbatim "intra_prediction.c" "static INLINE uint16_t get_dx" "get_dx"
Emit-Verbatim "intra_prediction.c" "void svt_av1_dr_prediction_z3_c" "svt_av1_dr_prediction_z3_c"
Emit-Verbatim "intra_prediction.c" "void svt_av1_dr_prediction_z1_c" "svt_av1_dr_prediction_z1_c"
Emit-Verbatim "intra_prediction.c" "void svt_av1_dr_prediction_z2_c" "svt_av1_dr_prediction_z2_c"
Emit-Verbatim "intra_prediction.c" "int32_t svt_aom_use_intra_edge_upsample" "svt_aom_use_intra_edge_upsample"
Emit-Macro "intra_prediction.c" "#define INTRA_EDGE_FILT" "INTRA_EDGE_FILT"
Emit-Macro "intra_prediction.c" "#define INTRA_EDGE_TAPS" "INTRA_EDGE_TAPS"
Emit-Verbatim "intra_prediction.c" "void svt_av1_filter_intra_edge_c" "svt_av1_filter_intra_edge_c"
Emit-Verbatim "intra_prediction.c" "int32_t svt_aom_intra_edge_filter_strength" "svt_aom_intra_edge_filter_strength"
Emit-Verbatim "intra_prediction.c" "static INLINE void dc_128_predictor" "dc_128_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void dc_left_predictor" "dc_left_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void dc_top_predictor" "dc_top_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void dc_predictor" "dc_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void v_predictor" "v_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void h_predictor" "h_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void smooth_predictor" "smooth_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void smooth_v_predictor" "smooth_v_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void smooth_h_predictor" "smooth_h_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE int abs_diff" "abs_diff"
Emit-Verbatim "intra_prediction.c" "static INLINE uint16_t paeth_predictor_single" "paeth_predictor_single"
Emit-Verbatim "intra_prediction.c" "static INLINE void paeth_predictor" "paeth_predictor"
Emit-Verbatim "intra_prediction.c" "void filter_intra_edge_corner" "filter_intra_edge_corner"
Emit-Verbatim "intra_prediction.c" "void svt_aom_dr_predictor" "svt_aom_dr_predictor"
Emit-Verbatim "intra_prediction.h" "enum {
    NEED_LEFT       = 1 << 1," "need-flags enum"
Emit-Verbatim "intra_prediction.c" "const uint8_t extend_modes" "extend_modes"
Emit-Verbatim "intra_prediction.h" "static const int32_t mode_to_angle_map" "mode_to_angle_map"
Emit-Verbatim "intra_prediction.h" "static INLINE int32_t av1_is_directional_mode" "av1_is_directional_mode"


# ---- C_DEFAULT upsample ----
Emit-Verbatim "intra_prediction_c.c" "void svt_av1_upsample_intra_edge_c" "svt_av1_upsample_intra_edge_c"

# ---- filterintra ----
Emit-Macro "filterintra_c.c" "#define FILTER_INTRA_SCALE_BITS" "FILTER_INTRA_SCALE_BITS"
Emit-Verbatim "filterintra_c.c" "DECLARE_ALIGNED(16, const int8_t, eb_av1_filter_intra_taps" "eb_av1_filter_intra_taps"
Emit-Verbatim "filterintra_c.c" "void svt_av1_filter_intra_predictor_c" "svt_av1_filter_intra_predictor_c"

# ---- SAD ----
Emit-Verbatim "compute_sad_c.c" "uint32_t NOINLINE svt_nxm_sad_kernel_helper_c" "svt_nxm_sad_kernel_helper_c"

# ---- quantizer (Q0) ----
Emit-Macro "definitions.h" "typedef int32_t TranLow" "TranLow"
Emit-Macro "definitions.h" "typedef uint8_t QmVal" "QmVal"
Emit-Verbatim "definitions.h" "static INLINE int32_t clamp" "clamp"
Emit-Macro "definitions.h" "#define MINQ" "MINQ"
Emit-Macro "definitions.h" "#define MAXQ" "MAXQ"
Emit-Macro "definitions.h" "#define QINDEX_RANGE" "QINDEX_RANGE"
Emit-Macro "inv_transforms.h" "#define AOM_QM_BITS" "AOM_QM_BITS"
Emit-Verbatim "inv_transforms.c" "static const int16_t ac_qlookup_QTX" "ac_qlookup_QTX"
Emit-Verbatim "inv_transforms.c" "static const int16_t dc_qlookup_QTX" "dc_qlookup_QTX"
Emit-Verbatim "inv_transforms.c" "int16_t svt_aom_dc_quant_qtx" "svt_aom_dc_quant_qtx"
Emit-Verbatim "inv_transforms.c" "int16_t svt_aom_ac_quant_qtx" "svt_aom_ac_quant_qtx"
Emit-Verbatim "inv_transforms.c" "int32_t svt_aom_get_qzbin_factor" "svt_aom_get_qzbin_factor"
Emit-Verbatim "inv_transforms.c" "void svt_aom_invert_quant" "svt_aom_invert_quant"
Emit-Verbatim "full_loop.c" "void svt_aom_quantize_b_c" "svt_aom_quantize_b_c"
Emit-Verbatim "full_loop.c" "static void quantize_fp_helper_c" "quantize_fp_helper_c"

# ---- build_intra_predictors with the documented get_filt_type shim ----
$r = Extract-Block $files["enc_intra_prediction.c"] "static void build_intra_predictors(const MacroBlockD* xd" "build_intra_predictors"
$shimmed = $r.body.Replace("const int32_t filt_type   = get_filt_type(xd, plane);", "const int32_t filt_type   = svtd_filt_type; /* SHIM: get_filt_type(xd, plane) replaced by generator shim (enc_intra_prediction.c:186); svtd_filt_type set per call */")
if ($shimmed -eq $r.body) {
    # try alternate spacing
    $shimmed = $r.body -replace "const int32_t filt_type\s*=\s*get_filt_type\(xd, plane\);", "const int32_t filt_type   = svtd_filt_type; /* SHIM: get_filt_type(xd, plane) -> generator shim */"
}
if ($shimmed -eq $r.body) { throw "get_filt_type shim substitution failed" }
Emit ""
Emit "// ==== SVT-AV1 enc_intra_prediction.c :$($r.line) - build_intra_predictors (verbatim EXCEPT the flagged get_filt_type shim) ===="
Emit $shimmed

Emit ""
$out.ToString() | Set-Content (Join-Path $PSScriptRoot "svt_gen.c") -Encoding ASCII
Write-Host "svt_gen.c written:" $out.Length "chars"

