# tools/golden_gen/extract.ps1
# Mechanically extracts VERBATIM functions/tables/macros from the vendored
# SVT-AV1 tree (third_party/SVT-AV1) into svt_gen.c. Never edits extracted
# text except the ONE documented substitution noted below. Fails loudly if
# any required symbol cannot be located.
#
# Usage:  powershell -ExecutionPolicy Bypass -File ./extract.ps1   (from this directory)
# Output: svt_gen.c  (gitignored? NO - committed output is regenerated by
#         running this script; see README.md)

$ErrorActionPreference = "Stop"

$repo = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$src  = Join-Path $repo "third_party\SVT-AV1\Source\Lib"
# Decoder side lives in the vendored aom_dsp subtree of the pinned tree
# (referenced by third_party/SVT-AV1/test/CMakeLists.txt:82).
$src3p = Join-Path $repo "third_party\SVT-AV1\third_party\aom_dsp"

$files = @{
    "transforms.c"       = (Get-Content (Join-Path $src "Codec\transforms.c") -Raw)
    "inv_transforms.c"   = (Get-Content (Join-Path $src "Codec\inv_transforms.c") -Raw)
    "inv_transforms.h"   = (Get-Content (Join-Path $src "Codec\inv_transforms.h") -Raw)
    "intra_prediction.c" = (Get-Content (Join-Path $src "Codec\intra_prediction.c") -Raw)
    "intra_prediction.h" = (Get-Content (Join-Path $src "Codec\intra_prediction.h") -Raw)
    "enc_intra_prediction.c" = (Get-Content (Join-Path $src "Codec\enc_intra_prediction.c") -Raw)
    "filterintra_c.c"    = (Get-Content (Join-Path $src "C_DEFAULT\filterintra_c.c") -Raw)
    "intra_prediction_c.c" = (Get-Content (Join-Path $src "C_DEFAULT\intra_prediction_c.c") -Raw)
    "compute_sad_c.c"    = (Get-Content (Join-Path $src "C_DEFAULT\compute_sad_c.c") -Raw)
    "full_loop.c"        = (Get-Content (Join-Path $src "Codec\full_loop.c") -Raw)
    "definitions.h"      = (Get-Content (Join-Path $src "Codec\definitions.h") -Raw)
    "common_utils.c"     = (Get-Content (Join-Path $src "Codec\common_utils.c") -Raw)
    "mode_decision.c"    = (Get-Content (Join-Path $src "Codec\mode_decision.c") -Raw)
    "EbConfigMacros.h"   = (Get-Content (Join-Path $repo "third_party\SVT-AV1\Source\API\EbConfigMacros.h") -Raw)
    "bitstream_unit.c"   = (Get-Content (Join-Path $src "Codec\bitstream_unit.c") -Raw)
    "bitstream_unit.h"   = (Get-Content (Join-Path $src "Codec\bitstream_unit.h") -Raw)
    "cabac_context_model.h" = (Get-Content (Join-Path $src "Codec\cabac_context_model.h") -Raw)
    "cabac_context_model.c" = (Get-Content (Join-Path $src "Codec\cabac_context_model.c") -Raw)
    "entropy_coding.c" = (Get-Content (Join-Path $src "Codec\entropy_coding.c") -Raw)
    "entdec.c"           = (Get-Content (Join-Path $src3p "src\entdec.c") -Raw)
    "entdec.h"           = (Get-Content (Join-Path $src3p "inc\entdec.h") -Raw)
    "bitreader.h"        = (Get-Content (Join-Path $src3p "inc\bitreader.h") -Raw)
    "bitreader.c"        = (Get-Content (Join-Path $src3p "src\bitreader.c") -Raw)
}
# normalize line endings to LF so multi-line patterns match regardless of
# how this script was saved
foreach ($k in @($files.Keys)) { $files[$k] = $files[$k].Replace("`r`n", "`n") }

function Find-Line([string]$text, [string]$pattern) {
    $pattern = $pattern.Replace("`r`n", "`n")
    $idx = $text.IndexOf($pattern, [System.StringComparison]::Ordinal)
    if ($idx -lt 0) { throw "symbol not found: $pattern" }
    $line = ($text.Substring(0, $idx) -split "`n").Count
    return @{ idx = $idx; line = $line }
}

# Extract a brace-balanced block starting at the line containing $pattern.
function Extract-Block([string]$text, [string]$pattern, [string]$label) {
    $loc = Find-Line $text $pattern
    $i = $text.IndexOf("{", $loc.idx)
    if ($i -lt 0) { throw "no opening brace for $label" }
    $depth = 0; $j = $i
    while ($j -lt $text.Length) {
        $c = $text[$j]
        if ($c -eq '{') { $depth++ }
        elseif ($c -eq '}') { $depth--; if ($depth -eq 0) { break } }
        $j++
    }
    if ($depth -ne 0) { throw "unbalanced braces for $label" }
    # include the remainder of the closing line (e.g. "} PredictionMode;")
    $lineEnd = $text.IndexOf("`n", $j)
    if ($lineEnd -lt 0) { $lineEnd = $text.Length }
    $end = $lineEnd
    $body = $text.Substring($loc.idx, $end - $loc.idx).TrimEnd()
    return @{ body = $body; line = $loc.line }
}

# Extract a preprocessor macro / scalar definition: from the pattern through
# its logical end (backslash continuations included), never crossing into
# unrelated constructs.
function Extract-Macro([string]$text, [string]$pattern, [string]$label) {
    $loc = Find-Line $text $pattern
    $lineStart = $text.LastIndexOf("`n", $loc.idx) + 1
    $pos = $lineStart
    while ($true) {
        $lineEnd = $text.IndexOf("`n", $pos)
        if ($lineEnd -lt 0) { $pos = $text.Length; break }
        $line = $text.Substring($pos, $lineEnd - $pos).TrimEnd("`r")
        $pos = $lineEnd + 1
        if (-not $line.TrimEnd().EndsWith('\')) { break }
    }
    $body = $text.Substring($lineStart, $pos - $lineStart).TrimEnd()
    return @{ body = $body; line = $loc.line }
}

# Extract a verbatim LINE RANGE: from the line containing $start through the
# line containing $end (both included). For declaration blocks that contain
# no braces, where Extract-Block cannot find the extent.
function Extract-Lines([string]$text, [string]$start, [string]$end, [string]$label) {
    $a = Find-Line $text $start
    $b = Find-Line $text $end
    if ($b.idx -lt $a.idx) { throw "end pattern before start pattern for $label" }
    $lineEnd = $text.IndexOf("`n", $b.idx)
    if ($lineEnd -lt 0) { $lineEnd = $text.Length }
    $body = $text.Substring($a.idx, $lineEnd - $a.idx).TrimEnd()
    return @{ body = $body; line = $a.line }
}

function Emit-Lines([string]$file, [string]$start, [string]$end, [string]$label) {
    $r = Extract-Lines $files[$file] $start $end $label
    Emit ""
    Emit "// ==== SVT-AV1 $file :$($r.line) - $label (verbatim line-range extract; do not edit) ===="
    Emit $r.body
}

function Emit-Macro([string]$file, [string]$pattern, [string]$label) {
    $r = Extract-Macro $files[$file] $pattern $label
    Emit ""
    Emit "// ==== SVT-AV1 $file :$($r.line) - $label (verbatim extract; do not edit) ===="
    Emit $r.body
}

$out = New-Object System.Text.StringBuilder
function Emit([string]$s) { [void]$out.AppendLine($s) }

function Emit-Verbatim([string]$file, [string]$pattern, [string]$label) {
    $r = Extract-Block $files[$file] $pattern $label
    Emit ""
    Emit "// ==== SVT-AV1 $file :$($r.line) - $label (verbatim extract; do not edit) ===="
    Emit $r.body
}

Emit "// ============================================================================"
Emit "// svt_gen.c - GENERATED by tools/golden_gen/extract.ps1 from the vendored"
Emit "// SVT-AV1 tree. Every marked block is a verbatim extract (provenance comment"
Emit "// above each). The only textual substitution in extracted code is the"
Emit "// get_filt_type shim inside build_intra_predictors, flagged inline below."
Emit "// Regenerate:  pwsh tools/golden_gen/extract.ps1"
Emit "// See tools/golden_gen/README.md for the provenance table."
Emit "// ============================================================================"
Emit "#include `"shims.h`""
Emit "#include <string.h>"
Emit "#include <stdio.h>"
Emit "#include <assert.h>"

# ---- definitions.h: enums / macros ----
Emit-Verbatim "definitions.h" "typedef enum ATTRIBUTE_PACKED {
    DC_PRED," "PredictionMode"

Emit-Verbatim "definitions.h" "typedef enum ATTRIBUTE_PACKED {
    FILTER_DC_PRED," "FilterIntraMode"

foreach ($d in @(
    @("definitions.h", "#define ROUND_POWER_OF_TWO(value, n)", "ROUND_POWER_OF_TWO"),
    @("definitions.h", "#define ROUND_POWER_OF_TWO_SIGNED(value, n)", "ROUND_POWER_OF_TWO_SIGNED"),
    @("definitions.h", "#define ANGLE_STEP", "ANGLE_STEP"))) {
    Emit-Macro $d[0] $d[1] $d[2]
}

# ---- common_utils.c: chroma (UV) mode folding (CH0) ----
# g_uv2y maps UvPredictionMode -> luma PredictionMode (UV_CFL_PRED ->
# DC_PRED, common_utils.c:14-31); get_uv_mode (common_utils.h:130-133) is
# the accessor.
Emit-Verbatim "common_utils.c" "const PredictionMode g_uv2y" "g_uv2y"
Emit-Verbatim "common_utils.c" "const PredictionMode fimode_to_intradir" "fimode_to_intradir"

# UvPredictionMode enum (definitions.h:1210-1227): UV_DC..UV_PAETH +
# UV_CFL_PRED, then UV_INTRA_MODES / UV_MODE_INVALID.
Emit-Verbatim "definitions.h" "typedef enum ATTRIBUTE_PACKED {
    UV_DC_PRED," "UvPredictionMode"

# ---- inv_transforms.h: helpers ----
Emit-Macro "inv_transforms.h" "#define INV_COS_BIT" "INV_COS_BIT"
Emit-Macro "inv_transforms.h" "#define MAX_TXWH_IDX" "MAX_TXWH_IDX"
Emit-Verbatim "inv_transforms.h" "static const int8_t inv_cos_bit_col" "inv_cos_bit_col"
Emit-Verbatim "inv_transforms.h" "static const int8_t inv_cos_bit_row" "inv_cos_bit_row"
Emit-Macro "inv_transforms.h" "static const int32_t cos_bit_min" "cos_bit_min"
Emit-Verbatim "inv_transforms.c" "const int32_t svt_aom_eb_av1_cospi_arr_data" "svt_aom_eb_av1_cospi_arr_data"
Emit-Verbatim "inv_transforms.c" "const int32_t svt_aom_eb_av1_sinpi_arr_data" "svt_aom_eb_av1_sinpi_arr_data"
Emit-Verbatim "inv_transforms.h" "static INLINE const int32_t* cospi_arr" "cospi_arr"
Emit-Verbatim "inv_transforms.h" "static INLINE const int32_t* sinpi_arr" "sinpi_arr"
Emit-Verbatim "inv_transforms.h" "static INLINE int32_t round_shift" "round_shift"
Emit-Verbatim "inv_transforms.h" "static INLINE int32_t half_btf" "half_btf"

# ---- transforms.c: forward kernels + config rows ----
Emit-Verbatim "transforms.c" "static const int8_t fwd_shift_4x4" "fwd_shift_4x4"
Emit-Verbatim "transforms.c" "const int8_t fwd_cos_bit_col" "fwd_cos_bit_col"
Emit-Verbatim "transforms.c" "const int8_t fwd_cos_bit_row" "fwd_cos_bit_row"
Emit-Verbatim "transforms.c" "void svt_av1_fdct4_new" "svt_av1_fdct4_new"
Emit-Verbatim "transforms.c" "void svt_av1_fadst4_new" "svt_av1_fadst4_new"
Emit-Verbatim "transforms.c" "static const int8_t fwd_shift_8x8" "fwd_shift_8x8"
Emit-Verbatim "transforms.c" "void svt_av1_fdct8_new" "svt_av1_fdct8_new"
Emit-Verbatim "transforms.c" "void svt_av1_fadst8_new" "svt_av1_fadst8_new"
Emit-Verbatim "transforms.c" "static const int8_t fwd_shift_16x16" "fwd_shift_16x16"
Emit-Verbatim "transforms.c" "void svt_av1_fdct16_new" "svt_av1_fdct16_new"
Emit-Verbatim "transforms.c" "void svt_av1_fadst16_new" "svt_av1_fadst16_new"
Emit-Verbatim "transforms.c" "static const int8_t fwd_shift_32x32" "fwd_shift_32x32"
Emit-Verbatim "transforms.c" "void svt_av1_fdct32_new" "svt_av1_fdct32_new"
Emit-Verbatim "transforms.c" "static void av1_fadst32_new" "av1_fadst32_new"
Emit-Verbatim "transforms.c" "static const int8_t fwd_shift_64x64" "fwd_shift_64x64"
Emit-Verbatim "transforms.c" "void svt_av1_fdct64_new" "svt_av1_fdct64_new"

# ---- inv_transforms.c: clamp / inverse kernels ----
Emit-Verbatim "definitions.h" "static INLINE int64_t clamp64" "clamp64"
Emit-Verbatim "inv_transforms.c" "static const int8_t inv_shift_4x4" "inv_shift_4x4"
Emit-Verbatim "inv_transforms.c" "static const int8_t inv_shift_8x8" "inv_shift_8x8"
Emit-Verbatim "inv_transforms.c" "static const int8_t inv_shift_16x16" "inv_shift_16x16"
Emit-Verbatim "inv_transforms.c" "static const int8_t inv_shift_32x32" "inv_shift_32x32"
Emit-Verbatim "inv_transforms.c" "static const int8_t inv_shift_64x64" "inv_shift_64x64"
Emit-Verbatim "inv_transforms.c" "static INLINE int32_t clamp_value" "clamp_value"
Emit-Verbatim "inv_transforms.c" "static INLINE void clamp_buf" "clamp_buf"
Emit-Verbatim "inv_transforms.c" "void svt_av1_idct4_new" "svt_av1_idct4_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_iadst4_new" "svt_av1_iadst4_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_idct8_new" "svt_av1_idct8_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_iadst8_new" "svt_av1_iadst8_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_idct16_new" "svt_av1_idct16_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_iadst16_new" "svt_av1_iadst16_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_idct32_new" "svt_av1_idct32_new"
Emit-Verbatim "inv_transforms.c" "static void av1_iadst32_new" "av1_iadst32_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_idct64_new" "svt_av1_idct64_new"
Emit-Verbatim "inv_transforms.c" "void svt_av1_round_shift_array_c" "svt_av1_round_shift_array_c"

# ---- intra_prediction.c: intra machinery ----
Emit-Macro "intra_prediction.c" "const int32_t sm_weight_log2_scale" "sm_weight_log2_scale"
Emit-Verbatim "intra_prediction.c" "const uint8_t sm_weight_arrays" "sm_weight_arrays"
Emit-Macro "intra_prediction.c" "#define sm_weights_sanity_checks" "sm_weights_sanity_checks"
Emit-Verbatim "intra_prediction.c" "static const uint16_t eb_dr_intra_derivative" "eb_dr_intra_derivative"
Emit-Macro "intra_prediction.c" "#define divide_round" "divide_round"
Emit-Verbatim "intra_prediction.c" "static INLINE uint16_t get_dy" "get_dy"
Emit-Verbatim "intra_prediction.c" "static INLINE uint16_t get_dx" "get_dx"
Emit-Verbatim "intra_prediction.c" "void svt_av1_dr_prediction_z3_c" "svt_av1_dr_prediction_z3_c"
Emit-Verbatim "intra_prediction.c" "void svt_av1_dr_prediction_z1_c" "svt_av1_dr_prediction_z1_c"
Emit-Verbatim "intra_prediction.c" "void svt_av1_dr_prediction_z2_c" "svt_av1_dr_prediction_z2_c"
Emit-Verbatim "intra_prediction.c" "int32_t svt_aom_use_intra_edge_upsample" "svt_aom_use_intra_edge_upsample"
Emit-Macro "intra_prediction.c" "#define INTRA_EDGE_FILT" "INTRA_EDGE_FILT"
Emit-Macro "intra_prediction.c" "#define INTRA_EDGE_TAPS" "INTRA_EDGE_TAPS"
Emit-Verbatim "intra_prediction.c" "void svt_av1_filter_intra_edge_c" "svt_av1_filter_intra_edge_c"
Emit-Verbatim "intra_prediction.c" "int32_t svt_aom_intra_edge_filter_strength" "svt_aom_intra_edge_filter_strength"
Emit-Verbatim "intra_prediction.c" "static INLINE void dc_128_predictor" "dc_128_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void dc_left_predictor" "dc_left_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void dc_top_predictor" "dc_top_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void dc_predictor" "dc_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void v_predictor" "v_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void h_predictor" "h_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void smooth_predictor" "smooth_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void smooth_v_predictor" "smooth_v_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE void smooth_h_predictor" "smooth_h_predictor"
Emit-Verbatim "intra_prediction.c" "static INLINE int abs_diff" "abs_diff"
Emit-Verbatim "intra_prediction.c" "static INLINE uint16_t paeth_predictor_single" "paeth_predictor_single"
Emit-Verbatim "intra_prediction.c" "static INLINE void paeth_predictor" "paeth_predictor"
Emit-Verbatim "intra_prediction.c" "void filter_intra_edge_corner" "filter_intra_edge_corner"
Emit-Verbatim "intra_prediction.c" "void svt_aom_dr_predictor" "svt_aom_dr_predictor"
Emit-Verbatim "intra_prediction.h" "enum {
    NEED_LEFT       = 1 << 1," "need-flags enum"
Emit-Verbatim "intra_prediction.c" "const uint8_t extend_modes" "extend_modes"
Emit-Verbatim "intra_prediction.h" "static const int32_t mode_to_angle_map" "mode_to_angle_map"
Emit-Verbatim "intra_prediction.h" "static INLINE int32_t av1_is_directional_mode" "av1_is_directional_mode"


# ---- C_DEFAULT upsample ----
Emit-Verbatim "intra_prediction_c.c" "void svt_av1_upsample_intra_edge_c" "svt_av1_upsample_intra_edge_c"

# ---- filterintra ----
Emit-Macro "filterintra_c.c" "#define FILTER_INTRA_SCALE_BITS" "FILTER_INTRA_SCALE_BITS"
Emit-Verbatim "filterintra_c.c" "DECLARE_ALIGNED(16, const int8_t, eb_av1_filter_intra_taps" "eb_av1_filter_intra_taps"
Emit-Verbatim "filterintra_c.c" "void svt_av1_filter_intra_predictor_c" "svt_av1_filter_intra_predictor_c"

# ---- SAD ----
Emit-Verbatim "compute_sad_c.c" "uint32_t NOINLINE svt_nxm_sad_kernel_helper_c" "svt_nxm_sad_kernel_helper_c"

# ---- quantizer (Q0) ----
Emit-Macro "definitions.h" "typedef int32_t TranLow" "TranLow"
Emit-Macro "definitions.h" "typedef uint8_t QmVal" "QmVal"
Emit-Verbatim "definitions.h" "static INLINE int32_t clamp" "clamp"
Emit-Macro "definitions.h" "#define MINQ" "MINQ"
Emit-Macro "definitions.h" "#define MAXQ" "MAXQ"
Emit-Macro "definitions.h" "#define QINDEX_RANGE" "QINDEX_RANGE"
Emit-Macro "inv_transforms.h" "#define AOM_QM_BITS" "AOM_QM_BITS"
Emit-Verbatim "inv_transforms.c" "static const int16_t ac_qlookup_QTX" "ac_qlookup_QTX"
Emit-Verbatim "inv_transforms.c" "static const int16_t dc_qlookup_QTX" "dc_qlookup_QTX"
Emit-Verbatim "inv_transforms.c" "int16_t svt_aom_dc_quant_qtx" "svt_aom_dc_quant_qtx"
Emit-Verbatim "inv_transforms.c" "int16_t svt_aom_ac_quant_qtx" "svt_aom_ac_quant_qtx"
Emit-Verbatim "inv_transforms.c" "int32_t svt_aom_get_qzbin_factor" "svt_aom_get_qzbin_factor"
Emit-Verbatim "inv_transforms.c" "void svt_aom_invert_quant" "svt_aom_invert_quant"
Emit-Verbatim "full_loop.c" "void svt_aom_quantize_b_c" "svt_aom_quantize_b_c"
Emit-Verbatim "full_loop.c" "static void quantize_fp_helper_c" "quantize_fp_helper_c"

# ---- entropy coder, encoder side (EC0) ----
# CDF probability plumbing first (cabac_context_model.h:38-47), then the
# od_ec window typedef + encoder context (bitstream_unit.h:92-120), byte
# swap + HToBE64 (bitstream_unit.h:154-218), then the encoder functions
# (bitstream_unit.c:77-408) in dependency order.
Emit-Macro "cabac_context_model.h" "#define CDF_PROB_BITS" "CDF_PROB_BITS"
Emit-Macro "cabac_context_model.h" "#define CDF_PROB_TOP" "CDF_PROB_TOP"
Emit-Macro "cabac_context_model.h" "#define AOM_ICDF" "AOM_ICDF"
Emit-Macro "bitstream_unit.h" "#define EC_PROB_SHIFT" "EC_PROB_SHIFT"
Emit-Macro "bitstream_unit.h" "#define EC_MIN_PROB" "EC_MIN_PROB"
Emit-Macro "bitstream_unit.h" "#define OD_BITRES" "OD_BITRES"
Emit-Macro "bitstream_unit.h" "#define OD_ICDF" "OD_ICDF"
Emit-Macro "bitstream_unit.h" "#define OD_ILOG_NZ" "OD_ILOG_NZ"
Emit-Macro "bitstream_unit.h" "typedef uint64_t OdEcWindow" "OdEcWindow"
Emit-Macro "bitstream_unit.h" "#define OD_EC_WINDOW_SIZE" "OD_EC_WINDOW_SIZE"
Emit-Macro "bitstream_unit.h" "#define OD_MEASURE_EC_OVERHEAD" "OD_MEASURE_EC_OVERHEAD"
Emit-Verbatim "bitstream_unit.h" "typedef struct OdEcEnc" "OdEcEnc"
# Encoder prototypes (bitstream_unit.h:122-131): the bitstream_unit.c extracts
# call each other (svt_od_ec_enc_init -> svt_od_ec_enc_reset); SVT declares
# them in this header block. OD_ARG_NONNULL / OD_WARN_UNUSED_RESULT resolve
# in shims.h.
Emit-Lines "bitstream_unit.h" "/*See entenc.c for further documentation.*/" "uint32_t svt_od_ec_enc_tell_frac" "encoder prototypes"
Emit-Verbatim "bitstream_unit.h" "static inline uint64_t BSwap64" "BSwap64"
# Documented deviation #2: the WORDS_BIGENDIAN #if guard around the HToLE/HToBE
# macro family (bitstream_unit.h:148-164) is dropped; the little-endian branch
# line is taken verbatim. The generator targets LE hosts (x86-64) only, where
# the guard's #else branch is the live one.
Emit-Macro "bitstream_unit.h" "#define HToBE64(X) BSwap64(X)" "HToBE64"
# svt_log2f = get_msb (definitions.h:592); the portable #else get_msb body
# (definitions.h:628-644) is extracted verbatim - same value floor(log2(n)).
# Must precede the encoder functions (od_ec_enc_normalize uses svt_log2f).
Emit-Macro "definitions.h" "#define svt_log2f get_msb" "svt_log2f"
Emit-Verbatim "definitions.h" "/*static*/ INLINE int32_t get_msb" "get_msb"
Emit-Verbatim "bitstream_unit.c" "static inline void propagate_carry_bwd" "propagate_carry_bwd"
Emit-Verbatim "bitstream_unit.c" "static NOINLINE void od_ec_enc_flush" "od_ec_enc_flush"
Emit-Verbatim "bitstream_unit.c" "static inline void svt_od_ec_enc_normalize" "svt_od_ec_enc_normalize"
Emit-Verbatim "bitstream_unit.c" "void svt_od_ec_enc_init" "svt_od_ec_enc_init"
Emit-Verbatim "bitstream_unit.c" "void svt_od_ec_enc_reset" "svt_od_ec_enc_reset"
Emit-Verbatim "bitstream_unit.c" "void svt_od_ec_enc_clear" "svt_od_ec_enc_clear"
Emit-Verbatim "bitstream_unit.c" "void svt_od_ec_encode_bool_eq_q15" "svt_od_ec_encode_bool_eq_q15"
Emit-Verbatim "bitstream_unit.c" "void svt_od_ec_encode_bool_q15" "svt_od_ec_encode_bool_q15"
Emit-Verbatim "bitstream_unit.c" "void svt_od_ec_encode_cdf_q15" "svt_od_ec_encode_cdf_q15"
Emit-Verbatim "bitstream_unit.c" "unsigned char* svt_od_ec_enc_done" "svt_od_ec_enc_done"
Emit-Verbatim "bitstream_unit.c" "int svt_od_ec_enc_tell" "svt_od_ec_enc_tell"
Emit-Verbatim "bitstream_unit.c" "uint32_t svt_od_ec_tell_frac" "svt_od_ec_tell_frac"
Emit-Verbatim "bitstream_unit.c" "uint32_t svt_od_ec_enc_tell_frac" "svt_od_ec_enc_tell_frac"

# ---- entropy coder, decoder side (EC0) ----
# entdec.c emits in source order (refill -> normalize -> init -> decode_bool
# -> decode_cdf -> tell -> tell_frac -> dec_tell_frac): every use follows its
# definition, no prototypes needed. The od_ec_dec struct (entdec.h:27-51)
# precedes them; it only needs OdEcWindow (already extracted).
Emit-Macro "entdec.h" "typedef struct od_ec_dec od_ec_dec;" "od_ec_dec typedef"
Emit-Verbatim "entdec.h" "struct od_ec_dec {" "od_ec_dec struct"
Emit-Macro "entdec.c" "#define OD_EC_LOTS_OF_BITS" "OD_EC_LOTS_OF_BITS"
Emit-Verbatim "entdec.c" "static void od_ec_dec_refill" "od_ec_dec_refill"
Emit-Verbatim "entdec.c" "static int od_ec_dec_normalize" "od_ec_dec_normalize"
Emit-Verbatim "entdec.c" "void od_ec_dec_init" "od_ec_dec_init"
Emit-Verbatim "entdec.c" "int od_ec_decode_bool_q15" "od_ec_decode_bool_q15"
Emit-Verbatim "entdec.c" "int od_ec_decode_cdf_q15" "od_ec_decode_cdf_q15"
Emit-Verbatim "entdec.c" "int od_ec_dec_tell" "od_ec_dec_tell"
Emit-Verbatim "entdec.c" "uint32_t od_ec_tell_frac" "od_ec_tell_frac"
Emit-Verbatim "entdec.c" "uint32_t od_ec_dec_tell_frac" "od_ec_dec_tell_frac"

# ---- CDF adaptation (EC2) ----
Emit-Macro "cabac_context_model.h" "typedef uint16_t AomCdfProb" "AomCdfProb"
Emit-Verbatim "cabac_context_model.h" "static INLINE void update_cdf" "update_cdf"
# Symbol wrappers with adaptation (EC2): the writer carries allow_update_cdf
# and the nsymbs==2 -> bool-encoder specialization (bitstream_unit.h:265-279);
# the reader side mirrors it (bitreader.h:84-98, bitreader.c:14-22).
Emit-Verbatim "bitstream_unit.h" "typedef struct AomWriter" "AomWriter"
Emit-Verbatim "bitstream_unit.h" "static INLINE void aom_stop_encode" "aom_stop_encode"
Emit-Verbatim "bitstream_unit.h" "static INLINE void aom_write_symbol" "aom_write_symbol"
Emit-Macro "bitreader.h" "#define ACCT_STR_PARAM" "ACCT_STR_PARAM"
Emit-Macro "bitreader.h" "#define ACCT_STR_ARG" "ACCT_STR_ARG"
Emit-Macro "bitreader.h" "#define aom_read_cdf" "aom_read_cdf macro"

# ---- intra-frame symbol surface (EC3) ----
# Non-RTC config defaults (EbConfigMacros.h:190-204): the generator builds
# with neither RTC_BUILD nor MINIMAL_BUILD, so the non-RTC section is the
# live one. Documented deviation #3: the CONFIG_ENABLE_FILTER_INTRA line is
# selected by VALUE (the =1 line, :203) and the RTC/MINIMAL #ifndef guard is
# dropped - on this build config it resolves to 1, making filter-intra
# signallable (mode_decision.c:108-119 predicate).
Emit-Macro "EbConfigMacros.h" "#define CONFIG_ENABLE_FILTER_INTRA          1" "CONFIG_ENABLE_FILTER_INTRA"
Emit-Macro "cabac_context_model.h" "#define CDF_SIZE" "CDF_SIZE"
Emit-Macro "cabac_context_model.h" "#define AOM_EXPAND_LIST" "AOM_EXPAND_LIST"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF2" "AOM_CDF2"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF3" "AOM_CDF3"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF4" "AOM_CDF4"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF5" "AOM_CDF5"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF6" "AOM_CDF6"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF7" "AOM_CDF7"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF8" "AOM_CDF8"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF9" "AOM_CDF9"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF10" "AOM_CDF10"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF11" "AOM_CDF11"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF12" "AOM_CDF12"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF13" "AOM_CDF13"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF14" "AOM_CDF14"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF15" "AOM_CDF15"
Emit-Macro "cabac_context_model.h" "#define AOM_CDF16" "AOM_CDF16"
Emit-Macro "cabac_context_model.h" "#define KF_MODE_CONTEXTS" "KF_MODE_CONTEXTS"
Emit-Verbatim "definitions.h" "typedef enum ATTRIBUTE_PACKED {
    BLOCK_4X4," "BlockSize"
Emit-Macro "definitions.h" "#define DIRECTIONAL_MODES" "DIRECTIONAL_MODES"
Emit-Macro "definitions.h" "#define MAX_ANGLE_DELTA" "MAX_ANGLE_DELTA"
Emit-Verbatim "common_utils.c" "const uint8_t intra_mode_context" "intra_mode_context"
Emit-Verbatim "common_utils.c" "const uint8_t block_size_wide" "block_size_wide"
Emit-Verbatim "common_utils.c" "const uint8_t block_size_high" "block_size_high"
Emit-Verbatim "cabac_context_model.c" "const AomCdfProb svt_aom_default_kf_y_mode_cdf" "svt_aom_default_kf_y_mode_cdf"
Emit-Verbatim "cabac_context_model.c" "static const AomCdfProb default_angle_delta_cdf" "default_angle_delta_cdf"
Emit-Verbatim "cabac_context_model.c" "static const AomCdfProb default_filter_intra_mode_cdf" "default_filter_intra_mode_cdf"
Emit-Verbatim "cabac_context_model.c" "static const AomCdfProb default_filter_intra_cdfs" "default_filter_intra_cdfs"
Emit-Verbatim "mode_decision.c" "int svt_aom_filter_intra_allowed_bsize" "svt_aom_filter_intra_allowed_bsize"
Emit-Verbatim "mode_decision.c" "int svt_aom_filter_intra_allowed(uint8_t enable_filter_intra" "svt_aom_filter_intra_allowed"
Emit-Verbatim "bitreader.h" "struct aom_reader" "aom_reader struct"
Emit-Macro "bitreader.h" "typedef struct aom_reader aom_reader;" "aom_reader typedef"
Emit-Verbatim "bitreader.c" "int aom_reader_init" "aom_reader_init"
Emit-Verbatim "bitreader.h" "static INLINE int aom_read_cdf_" "aom_read_cdf_"
Emit-Verbatim "bitreader.h" "static INLINE int aom_read_symbol_" "aom_read_symbol_"

# ---- partition symbol surface (ECP1) ----
# Context derivation inputs (entropy_coding.c:945-960): partition_context_lookup
# (definitions.h:1547-1574) written per coded block over the block's mi extent
# (coding_loop.c:1700-1713); INVALID_NEIGHBOR_DATA (definitions.h:334, 0xFF)
# fresh cells map to 0. Alphabet per svt_aom_partition_cdf_length
# (entropy_coding.c:922-930): 10 symbols (EXT_PARTITION_TYPES) for 16x16/32x32/
# 64x64, 4 (PARTITION_TYPES) for 8x8, 8 for 128x128. Gather helpers
# (cabac_context_model.h:373-405) feed the XOR-edge 2-symbol branches
# (:970-977). default_partition_cdf (cabac_context_model.c:134-155,
# PARTITION_CONTEXTS = PARTITION_BLOCK_SIZES * PARTITION_PLOFFSET = 20 rows).
Emit-Macro "definitions.h" "#define INVALID_NEIGHBOR_DATA" "INVALID_NEIGHBOR_DATA"
Emit-Macro "definitions.h" "typedef char PartitionContextType;" "PartitionContextType"
Emit-Verbatim "definitions.h" "typedef enum ATTRIBUTE_PACKED {
    PARTITION_NONE," "PartitionType"
Emit-Macro "definitions.h" "#define PARTITION_PLOFFSET" "PARTITION_PLOFFSET"
Emit-Macro "definitions.h" "#define PARTITION_BLOCK_SIZES" "PARTITION_BLOCK_SIZES"
Emit-Macro "definitions.h" "#define PARTITION_CONTEXTS" "PARTITION_CONTEXTS"
Emit-Lines "definitions.h" "static const struct
{
    PartitionContextType above;" "};

/* clang-format on */" "partition_context_lookup"
Emit-Verbatim "cabac_context_model.h" "static AomCdfProb cdf_element_prob" "cdf_element_prob"
Emit-Verbatim "cabac_context_model.h" "static INLINE void partition_gather_horz_alike" "partition_gather_horz_alike"
Emit-Verbatim "cabac_context_model.h" "static INLINE void partition_gather_vert_alike" "partition_gather_vert_alike"
Emit-Verbatim "cabac_context_model.c" "static const AomCdfProb default_partition_cdf" "default_partition_cdf"
Emit-Verbatim "entropy_coding.c" "int32_t svt_aom_partition_cdf_length" "svt_aom_partition_cdf_length"

# ---- skip symbol surface (ECP2) ----
# skip_cdfs (cabac_context_model.h:323, SKIP_CONTEXTS definitions.h:1313);
# defaults (cabac_context_model.c:594-596, COPY_CDF :781); the symbol is the
# FIRST arithmetic-coded symbol of each I_SLICE block for our config
# (write_modes_b :4980-4985 via encode_skip_coeff_av1 :995-1000, context =
# above_skip + left_skip of the neighbor mbmis, :983-989).
Emit-Macro "definitions.h" "#define SKIP_CONTEXTS" "SKIP_CONTEXTS"
Emit-Verbatim "cabac_context_model.c" "static const AomCdfProb default_skip_cdfs" "default_skip_cdfs"

# ---- build_intra_predictors with the documented get_filt_type shim ----
$r = Extract-Block $files["enc_intra_prediction.c"] "static void build_intra_predictors(const MacroBlockD* xd" "build_intra_predictors"
$shimmed = $r.body.Replace("const int32_t filt_type   = get_filt_type(xd, plane);", "const int32_t filt_type   = svtd_filt_type; /* SHIM: get_filt_type(xd, plane) replaced by generator shim (enc_intra_prediction.c:186); svtd_filt_type set per call */")
if ($shimmed -eq $r.body) {
    # try alternate spacing
    $shimmed = $r.body -replace "const int32_t filt_type\s*=\s*get_filt_type\(xd, plane\);", "const int32_t filt_type   = svtd_filt_type; /* SHIM: get_filt_type(xd, plane) -> generator shim */"
}
if ($shimmed -eq $r.body) { throw "get_filt_type shim substitution failed" }
Emit ""
Emit "// ==== SVT-AV1 enc_intra_prediction.c :$($r.line) - build_intra_predictors (verbatim EXCEPT the flagged get_filt_type shim) ===="
Emit $shimmed

Emit ""
$out.ToString() | Set-Content (Join-Path $PSScriptRoot "svt_gen.c") -Encoding ASCII
Write-Host "svt_gen.c written:" $out.Length "chars"

